#! /bin/bash
### 编译程序
go build

### 编译后的文件移到指定目录下
mv ./superconsumer /usr/bin/superconsumer && chmod a+x /usr/sbin/superconsumer

### 创建配置文件与服务进程管理脚本
mv ./config/superconsumer.json /etc/superconsumer.json
mv ./superconsumerd /etc/init.d/superconsumerd && chmod a+x /etc/init.d/superconsumerd

