#! /bin/bash
### 编译程序
go get github.com/go-ozzo/ozzo-config
go get github.com/bsm/sarama-cluster
go get github.com/Shopify/sarama
go get github.com/go-ozzo/ozzo-log
go build

### 编译后的文件移到指定目录下
mv ./superconsumer /usr/bin/superconsumer && chmod a+x /usr/sbin/superconsumer

### 创建配置文件与服务进程管理脚本
mv ./config/superconsumer.json /etc/superconsumer.json
mv ./superconsumerd /etc/init.d/superconsumerd && chmod a+x /etc/init.d/superconsumerd

